server {
    listen 443 ssl;
    server_name api.kyw511.ddns.net;

    # SAN(Subject Alternative Name) 인증서
    ssl_certificate /etc/letsencrypt/live/kyw511.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kyw511.ddns.net/privkey.pem;

    # nginx - backend 통신이 내부 통신으로만 하니까 http로 충분 (https는 오버헤드가 발생함)
    # 만약 nginx - backend 가 외부 네트워크를 사용한 통신을 한다면 https로 바꿔야 함!!
    location / {
        proxy_pass http://commerce-backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
