server {
    listen 80;
    server_name api.kyw511.ddns.net;

    # 인증서 발급/갱신
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 나머지는 전부 HTTPS로
    location / {
        return 301 https://$host$request_uri;
    }
}